### ISSUE TITLE
open("wifi") doesnt work on IOS

### ISSUE THREAD

**Issue by ifbbprochris** [guyromb/cordova-open-native-settings#38] opened 2018-11-09 07:35 UTC

**Comment by andreasalvi** [comment] 2019-05-14 11:11
On android works fine but on iOS it brings me to General Settings. Any news?

**Comment by angelo-italy** [comment] 2019-05-14 13:53
Same problem here. Testing on ios12

**Comment by angelofan** [comment] 2019-11-29 04:35
same issue

**Comment by tshepo-choshi** [comment] 2021-02-10 21:09
Hi, has this issue been resolved?
What's another alternative solution that can be used?

**Comment by timbru31** [comment] 2021-02-11 11:11
The most recent update (v1.5.3) fixed the issue - I can confirm it working for iOS 13.6 and iOS 14.5 (beta 1). @guyromb maybe you can close this issue here?

**Comment by tshepo-choshi** [comment] 2021-02-11 11:16
I tested v1.5.3 on iOS and its returning the following error: 
"The old format of this exec call has been removed (deprecated since 2.1).  Change to: cordova.exec(null,null......"  etc

**Comment by timbru31** [comment] 2021-02-11 12:08
Either correct your syntax to call the plugin or update your cordova-ios, the exec signature in https://github.com/guyromb/cordova-open-native-settings/blob/master/www/settings.js#L6 is correct. That has nothing to do with this issue though.

**Comment by guyromb** [comment] 2021-02-11 14:58
Resolved in v1.5.3

**Closed by guyromb** 2021-02-11 14:58 UTC
